function H_3x3 = computeHomography(src_pts_nx2, dest_pts_nx2)
    A = [];
    for i = 1:size(src_pts_nx2,1)
        A = [A; src_pts_nx2(i,1), src_pts_nx2(i,2), 1, 0, 0, 0, ...
            -1.*dest_pts_nx2(i,1).*src_pts_nx2(i,1), ...
            -1.*dest_pts_nx2(i,1).*src_pts_nx2(i,2), -1.*dest_pts_nx2(i,1)];
        A = [A; 0,0,0, src_pts_nx2(i,1), src_pts_nx2(i,2), 1, ...
            -1.*dest_pts_nx2(i,2).*src_pts_nx2(i,1), ...
            -1.*dest_pts_nx2(i,2).*src_pts_nx2(i,2), -1.*dest_pts_nx2(i,2)];
    end
    [h,D] = eig(A'*A);
    H_3x3 = reshape(h(:,1),[3,3])';
end